# Generated by Django 2.1.1 on 2018-09-11 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApellidoPaterno', models.CharField(max_length=35)),
                ('ApellidoMaterno', models.CharField(max_length=35)),
                ('Nombres', models.CharField(max_length=35)),
                ('DN1', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCurso', models.CharField(max_length=50)),
                ('Creditos', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alumno', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.Alumno')),
                ('Curso', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.Curso')),
            ],
        ),
    ]
